#!/usr/bin/env bash
# seed-gallery-fixture.sh — write a reproducible Phase 2 gallery fixture.
#
# Creates <dir>/ai.csv, <dir>/linux.csv, <dir>/design.csv (+ decoys that must be
# ignored: index.json, linux.csv.bak, .hidden.csv, notes.txt) with rows that
# exercise the gallery read path:
#
#   * a 4-media tweet, a 3-media tweet, a 2-media tweet, a 1-media tweet
#   * text-only tweets (media = [])
#   * an empty collection (design.csv: header only)
#   * a malformed media cell and a malformed (short) row inside ai.csv
#   * searchable author/username/text mixes ("wayland", "Linux", "@linuxguy")
#   * newest tweet == newest bookmark == row 1, so every sort mode has an
#     unambiguous expected first row:
#         saved_desc / tweet_desc -> ...001
#         saved_asc  / tweet_asc  -> ...008
#
# CSV is generated by python3's csv.writer, so the JSON `media` cells are
# correctly quoted (inner quotes doubled). Hand-writing those cells through a
# shell heredoc produces invalid CSV — `,"[""u1"",""u2""]"` vs `,"["u1","u2"]"` —
# which a correct reader must then reject as malformed rows.
#
# Usage:
#   scripts/seed-gallery-fixture.sh [DIR] [--fresh]
#     DIR      storage dir to write (default: a fresh mktemp dir)
#     --fresh  delete DIR first
#
# Prints the storage dir as the final stdout line:
#   DIR=$(scripts/seed-gallery-fixture.sh /tmp/twbm-fixture --fresh | tail -1)

set -euo pipefail

DIR="${1:-}"
FRESH=""
if [ "${2:-}" = "--fresh" ]; then FRESH=1; fi
if [ -z "$DIR" ]; then DIR="$(mktemp -d "${TMPDIR:-/tmp}/twbm-fixture.XXXXXX")"; fi

if [ -n "$FRESH" ]; then rm -rf "$DIR"; fi
mkdir -p "$DIR"

python3 - "$DIR" <<'PY'
import csv, datetime, json, os, sys

d = sys.argv[1]
now = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0)


def ts(days_ago):
    return (now - datetime.timedelta(days=days_ago)).strftime("%Y-%m-%dT%H:%M:%SZ")


def media(*names):
    return json.dumps([f"https://pbs.twimg.com/media/{n}.jpg" for n in names])


HEADER = ["url", "media", "author", "username", "tweet_date", "saved_at", "text"]


def write(name, rows):
    with open(os.path.join(d, name), "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(HEADER)
        for row in rows:
            w.writerow(row)


# linux.csv — 8 valid rows. tweet_date and saved_at both run newest(row1) -> oldest(row8).
linux = [
    ["https://x.com/linuxguy/status/1000000000000000001", media("a1", "a2", "a3", "a4"),
     "Linux Guy", "@linuxguy", ts(1), ts(0),
     "Wayland on Linux: a four-image thread about compositors, tearing, and HiDPI."],
    ["https://x.com/linuxguy/status/1000000000000000002", media("b1", "b2", "b3"),
     "Linux Guy", "@linuxguy", ts(2), ts(1),
     "Terminal workflows that survive a reinstall — three screenshots."],
    ["https://x.com/tilingfan/status/1000000000000000003", media("c1", "c2"),
     "Tiling Fan", "@tilingfan", ts(3), ts(2),
     "My tiling setup after two years, two images."],
    ["https://x.com/kernelnotes/status/1000000000000000004", media("d1"),
     "Kernel Notes", "@kernelnotes", ts(4), ts(3),
     "One screenshot of the new scheduler trace view."],
    ["https://x.com/linuxguy/status/1000000000000000005", media(),
     "Linux Guy", "@linuxguy", ts(5), ts(4),
     "Text-only: why I finally stopped distro hopping. No media here."],
    ["https://x.com/shellpilled/status/1000000000000000006", media(),
     "Shell Pilled", "@shellpilled", ts(6), ts(5),
     "Text-only: a short note on POSIX shell quoting."],
    ["https://x.com/linuxguy/status/1000000000000000007", media("c1", "c2"),
     "Linux Guy", "@linuxguy", ts(7), ts(6),
     "Wayland vs X11, again — but with benchmarks this time."],
    ["https://x.com/tilingfan/status/1000000000000000008", media("d1"),
     "Tiling Fan", "@tilingfan", ts(8), ts(7),
     "A single screenshot of the new status bar."],
]
write("linux.csv", linux)

# ai.csv — valid rows, a malformed media cell, and a malformed (1-field) row.
ai = [
    ["https://x.com/aiperson/status/2000000000000000001", media("d1"),
     "AI Person", "@aiperson", ts(9), ts(1),
     "Local models are finally good enough for a personal archive."],
    ["https://x.com/aiperson/status/2000000000000000002", "not-json",
     "AI Person", "@aiperson", ts(10), ts(2),
     "This row has a broken media cell and must still render as a text card."],
    ["https://x.com/aiperson/status/2000000000000000003", media(),
     "AI Person", "@aiperson", ts(11), ts(3),
     "Text-only thinking about retrieval without a vector database."],
    # malformed row: a single field; must be skipped without losing the file
    ["https://x.com/aiperson/status/2000000000000000004"],
    ["https://x.com/promptsmith/status/2000000000000000005", media("c1", "c2"),
     "Prompt Smith", "@promptsmith", ts(13), ts(4),
     "Two images of an eval dashboard."],
]
write("ai.csv", ai)

# design.csv — valid CSV, header only => a collection with 0 posts and 0 media.
write("design.csv", [])

# decoys that must never be treated as collections
with open(os.path.join(d, "index.json"), "w") as fh:
    fh.write('{"version":1,"tweets":[]}\n')
with open(os.path.join(d, "linux.csv"), encoding="utf-8") as src:
    body = src.read()
for decoy in ("linux.csv.bak", ".hidden.csv"):
    with open(os.path.join(d, decoy), "w", encoding="utf-8") as fh:
        fh.write(body)
with open(os.path.join(d, "notes.txt"), "w") as fh:
    fh.write("not a csv\n")
PY

echo "seeded fixture:" >&2
echo "  $DIR" >&2
ls -1a "$DIR" | grep -v '^\.$\|^\.\.$' >&2
echo "$DIR"
